### get all users API URL
GET http://localhost:8080/api/users/

### get user by id API URL
GET http://localhost:8080/api/user/61e010da15e34cc5ec2116ff

### get user by username API URL
GET http://localhost:8080/api/user-username/Test

### add user API URL
POST http://localhost:8080/api/user/
content-type: application/json

{
	"username": "Test",
	"password": "testpassword",
    "email": "test@hotmail.com"
}

### update user API URL
PUT http://localhost:8080/api/user/61e14c8596647ac5ef87ca50
content-type: application/json

{
	"password": "TestUpdatePassword"
}

### update user score API URL
PUT http://localhost:8080/api/add-score/61e1bc1deb75c9216b1c37de
content-type: application/json

{
	"scores": {
		"distancePays": 10,
		"distanceVilles": 10,
		"populationPays": 10,
		"populationVilles": 0
	}
}

### compare a user password API URL
PUT http://localhost:8080/api/user/compare-password/61e2badbfd4e788fe9107a78
content-type: application/json

{
	"password": "kiki123"
}

### login user
POST http://localhost:8080/api/login
Content-Type: application/json

{
	"username": "kirsan",
	"password": "kiki"
}

### remove a user by id 
DELETE http://localhost:8080/api/user/61e14b21342763fa8af1a614

### remove a user by username 
DELETE http://localhost:8080/api/user-username/koko


###
POST https://countriesnow.space/api/v0.1/countries/population
content-type: application/json

{
	"country":"Germany"
}