### get all users API URL
GET http://localhost:3002/api/users/

### get user by id API URL
GET http://localhost:3002/api/user/61e010da15e34cc5ec2116ff

### add user API URL
POST http://localhost:3002/api/user/
content-type: application/json

{
	"username": "Test",
	"password": "testpassword",
    "email": "test@hotmail.com"
}

### update user API URL
PUT http://localhost:3002/api/user/61e010da15e34cc5ec2116ff
content-type: application/json

{
	"username": "TestUpdate"
}

### update user score API URL
PUT http://localhost:3002/api/add-score/61e010da15e34cc5ec2116ff
content-type: application/json

{
	"scores": {
		"distancePays": 290,
		"distanceVilles": 600,
		"populationPays": 1000,
		"populationVilles": 100
	}
}

### login user
POST http://localhost:3002/api/login
Content-Type: application/json

{
	"username": "test",
	"password": "00000"
}

### remove a user
DELETE http://localhost:3002/api/user/61e01059d5e7074ef3e4d9fa