### get all users API URL
GET http://localhost:3002/api/users/

### get user by id API URL
GET http://localhost:3002/api/user/61caee7f20a8bd234109db6

### add user API URL
POST http://localhost:3002/api/user/
content-type: application/json

{
	"username": "Test",
	"password": "testpassword",
    "email": "test@hotmail.com"
}

### update user API URL
PUT http://localhost:3002/api/user/61cae7cbceef2d430a317399
content-type: application/json

{
	"username": "TestUpdate"
}

### login user
POST http://localhost:3002/api/login
Content-Type: application/json

{
	"username": "test",
	"password": "00000"
}

### remove a user
DELETE http://localhost:3002/api/user/61cae7cbceef2d430a317399